### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by UnluckyY1** [devdennysegura/nodejs-server-Flutter-Netflix-App#1]
C:\src\nodejs-server-Flutter-Netflix-App-master>git clone git@github.com:DennySegura/netflix-app.git
Cloning into 'netflix-app'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists. 
btw i have no clue with node.js so i hope u cold help with that

**Comment by Monasha1992** [comment]
Download the Zip file

**Comment by devdennysegura** [comment]
@UnluckyY1  clone via ssh or https?

**Comment by esQmo** [comment]
@devdennysegura Hey, same problem here, I'm facing access restricted error as well. Can you make a more clearer set up steps? Should we run `git clone git@github.com:DennySegura/netflix-app.git ` inside **nodejs-server-Flutter-Netflix-App-master** folder?
